version: "3"

volumes:
  h2-data:
    driver: local

services:
  # H2 database
  h2:
    image: oscarfonts/h2:2.1.210
    container_name: h2
    restart: always
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - h2-data:/opt/h2-data
      - /Users/Shared/h2/h2-data:/opt/h2-data

# docker run -d -p 1521:1521 -p 81:81 -v //Users/Shared/h2/h2-data::/opt/h2-data --name=h2 oscarfonts/h2:2.1.210
# docker-compose -f ./docker-compose-h2-standalone.yml up -d
